apiVersion: v1
kind: Service

metadata:
  name: skillforge-api
  namespace: skillforge

spec:
  selector:
    app: skillforge-api

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: ClusterIP