apiVersion: v1
kind: Service

metadata:
  name: skillforge-service
  namespace: skillforge

spec:
  type: NodePort

  selector:
    app: skillforge

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080